pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
authors:
  hleinone:
    display_name: Hannu Leinonen
    gravatar: 4ecca0c7c3d725a2f73c77de52ff2c78
    email: hleinone@gmail.com
    web: http://javanto.com/
    stackoverflow: 
      id: 83047
      name: hleinone
    github: hleinone
  javanto:
    display_name: Javanto
    gravatar: b166121e7a60bd0dac342d77f63fbdb7
    web: http://javanto.com/
    github: javanto
