pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
authors:
  hleinone:
    display_name: Hannu Leinonen
    gravatar: 4ecca0c7c3d725a2f73c77de52ff2c78
    email: hleinone@gmail.com
    web: http://javanto.com/
    linkedin: hleinone
    google_plus: 108633196639533658351
    twitter: hleinone
    identica: hleinone
    aboutme: hleinone
    stackoverflow_careers: hleinone
    stackoverflow: 
      id: 83047
      name: hleinone
    github: hleinone
    google_code: hleinone
    bitbucket: hleinone
  javanto:
    display_name: Javanto
    gravatar: b166121e7a60bd0dac342d77f63fbdb7
    web: http://javanto.com/
    google_plus: 100706528962511883803
    twitter: javantocom
    github: javanto
